remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Secure RDMA with Pure IB Verbs
description: Zero-Copy Networking with Replay Attack Prevention - Revolutionary RDMA implementation using pure InfiniBand verbs for complete PSN control
show_downloads: true
github:
  repository_url: https://github.com/linjiw/rmda-multi-client
  zip_url: https://github.com/linjiw/rmda-multi-client/archive/refs/heads/main.zip
  tar_url: https://github.com/linjiw/rmda-multi-client/archive/refs/heads/main.tar.gz